ebi-ait/ingest-archiver

config.py
requirements-dev.txt
requirements.txt
tests/json/usi/sequencing_experiment.json
tests/json/usi/sequencing_run.json
tests/json/usi/sequencing_run_10x.json
tests/test_archiver.py
tests/test_converter.py
tests/test_usi_api.py

- Mock some tests
- Mark others as integration tests, to avoid long running tasks
- Tear down API connections, to avoid open socket errors.
- Add Environment Variable `AAP_API_USER`

Fix Unit Tests

---

api/ontology.py
archiver/archiver.py
archiver/converter.py
archiver/dsp_post_process.py
archiver/ena_sequencing_experiment.py
archiver/instrument_model.py
archiver/project.py
cli.py
conversion/json_mapper.py
json2json_setup.py
tests/archiver/test_instrument_model.py
tests/conversion/test_json_mapper.py
tests/json/dsp/sequencing_experiment.json
tests/json/dsp/study.json
tests/json/hca/library_preparation_protocol.json
tests/json/hca/sequencing_protocol.json
tests/test_converter.py

Changes in this pull request:
* Updates to `StudyConverter`.
* Modified JSON mapper to make non-existent anchored nodes optional.

More changes to conversion

---

Dockerfile
README.md
api/ingest.py
archiver/archiver.py
archiver/converter.py
cli.py
requirements.txt
utils/protocols.py

- Only import primary manifests when importing from project
- Add --no_validation mode to not send to DSP
- Consistent File and Conversion Map Formats
- Add 10x Library Constructions
- Run in Docker Container

Bugfixes for Production Usage

---

api/ontology.py
archiver/archiver.py
cli.py

Include DCP Bundle UUID if it exists, so that file-archiver will download files from the DCP for archiving.
Plus fixes for Ontology API, CLI, and passing Manifest files.
Implementation for [Ticket #94](https://github.com/ebi-ait/hca-ebi-dev-team/issues/94)

DCP Download

---

archiver/archiver.py

Tested in USI Test and Dev: http://wwwdev.ebi.ac.uk/biosamples/samples/SAMEA7074321
ticket: ebi-ait/hca-ebi-dev-team#149

Support submission of multiple "derived from" biomaterials

---

tests/test_protocols.py
utils/protocols.py

ticket: ebi-ait/hca-ebi-dev-team#310

If sequencing experiment is using CITE-seq, use 10xV2 bam conversion for sequencing runs

---

api/ontology.py
archiver/biosamples.py
archiver/converter.py
archiver/dsp_post_process.py
archiver/ena.py
archiver/ena_sequencing_experiment.py

Move code from #26 into common location and use for ENA Ontology Lookups.
Otherwise the terms specified in the HCA may be lost when archived.
Deployed to Dev

ENA Ontology Bug

---

Dockerfile

ebi-ait/hca-ebi-wrangler-central#178

Source python base image from quay.io

---

api/ontology.py

This change is a temporary fix to the following archiver error:
```
ingest-archiver-845f5f9f47-vp9ck ingest-archiver [_internal.py:113 -                 _log() ] 2021-01-19 19:26:05,907 - werkzeug - INFO - 10.70.1.47 - - [19/Jan/2021 19:26:05] "POST /archiveSubmissions HTTP/1.1" 200 -
ingest-archiver-845f5f9f47-vp9ck ingest-archiver [app.py:109 -        async_archive() ] 2021-01-19 19:26:09,303 - __main__ - ERROR - Could not find EFO:0008995
ingest-archiver-845f5f9f47-vp9ck ingest-archiver Traceback (most recent call last):
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File "app.py", line 99, in async_archive
ingest-archiver-845f5f9f47-vp9ck ingest-archiver     entity_map: ArchiveEntityMap = archiver.convert(manifests)
ingest-archiver-845f5f9f47-vp9ck ingest-archiver   File …
```

Putting back the ontology search function for checking 10x

---

hca/loader.py
hca/submission.py
requirements-dev.txt
utils/duplicate/archiver.py
utils/duplicate/cli.py
utils/duplicate/loader.py
utils/duplicate/submission.py

Utility for testing the archiver by reconverting production entities with accessions as new entities without accession to dev / staging environments and comparing the result.

Archiving Test Utility

---

api/ontology.py
tests/api/test_ontology.py
utils/protocols.py

Replace usage of findByIdAndIsDefiningOntology endpoint

---

config.py
converter/biostudies.py
tests/unit/converter/test_biostudies_converter.py

dcp-448
Changes:
- Change environment variable names for BioStudies
- Fix the conversion structure for Funding for BioStudies archiving

dcp-448/Fix funding payload to bst

---

app.py
archiver/direct.py
converter/biosamples.py
requirements.txt
submitter/base.py
submitter/biosamples.py
submitter/biosamples_submitter_service.py
tests/resources/biomaterial_entity.json
tests/unit/submitter/test_biosamples_submitter.py
tests/unit/submitter/test_biosamples_submitter_service.py
tests/unit/submitter/test_biostudies_submitter_service.py

ebi-ait/dcp-ingest-central#497
Changes:
- Add biostudies links to related biosamples in the BioSamples archive

[dcp-497] Add biostudies links to biosamples

---

hca/submission.py
tests/unit/hca/test_submission.py

dcp-531
dcp-448
Changes:
- Add BioStudies accession to ingest's project entity

[dcp-531] Add BioStudies accession to ingest's project entity

---

README.md
doc/sequencediagram.txt

- updated the sequence diag to use plantuml syntax
- added diag to README

updated sequence diag to plantuml syntax

---

README_for_direct_archiver.md
archiver/direct.py
requirements.txt
submit_to_archives.py
submitter/base.py

**Changes**:
This is the 1st iteration of this script. It only needs the submission UUID as a parameter. You can configure the environment you would like to run in the `ENVIRONMENT` variable in the script or you could set it as an environment variable.
**Known issue**: If a study has been already submitted to ENA you can not submit it again. ENA sends an error response. The script is currently not processing that error response. I am going to create a ticket for that job.

[dcp-581] add test script for direct archiving

---

converter/ena/base.py
converter/schema_processor.py
submitter/base.py
tests/unit/converter/test_schema_processor.py

Changes:
- small code clean-up
- Add a script that helps extracting property values from the schema document and able to create a csv output to use if for the mapping document: [Mapping HCA biomaterial attributes to ENA sample attributes](https://docs.google.com/spreadsheets/d/18LvAf8wv-yGV552kk0R3SlGf5oEmAyKdKZ2OMk9QMWk/edit#gid=1421951667)
see ebi-ait/dcp-ingest-central#615

[dcp-615] Creating a mapping document for biomaterial schema

---

converter/biosamples.py
converter/ena/ena_study.py
hca/accession_mapper.py
hca/submission.py
submit_to_archives.py
submitter/base.py
submitter/ena.py
tests/unit/hca/test_accession_mapper.py
tests/unit/hca/test_submission.py
tests/unit/hca/test_updater.py
tests/unit/submitter/test_biosamples_submitter.py
tests/unit/submitter/test_biostudies_submitter.py
tests/unit/submitter/test_ena_submitter.py
tests/unit/utils.py

Changes:
- Populate entities with archive accessions

[dcp-531] Add archive accessions to entities

---

README_for_direct_archiver.md
archiver/__init__.py
archiver/direct.py
converter/ena/base.py
submit_to_archives.py
submitter/base.py
submitter/biosamples.py
submitter/biostudies.py
submitter/ena.py
tests/unit/submitter/test_biosamples_submitter.py
tests/unit/submitter/test_biostudies_submitter.py
tests/unit/submitter/test_ena_submitter.py

#dcp-ingest-central/dcp-708
Changes:
- Refined archiving response
- README updated with the latest response format

[dcp-708] Refined archiving response

---

README_for_direct_archiver.md
archiver/direct.py
archiver_app.py
converter/ena/base.py
converter/ena/ena_experiment.py
converter/ena/ena_receipt.py
converter/ena/ena_run.py
hca/assay.py

Ticket: https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/708

dcp 708 ENA experiment and run archive integration

---

submit_to_archives.py

dcp-729
Changes:
- Handle not OK HTTP response from archiver

[dcp-729] Handle not OK HTTP response from archiver

---

archiver/direct.py
submitter/biosamples.py
tests/unit/submitter/test_biosamples_submitter.py

dcp-745
Changes:
- This change handle HTTPError from BioSamples service. This came up in case of missing biomaterials name,
but could be useful for any other HTTP related error.
It processes all the biomaterials and tries to submit them to BioSamples service. If collects all the responses and checks them. If there is even 1 error, then it stops archiving and returns the response to the user with the error messages.
I wanted to process all the biomaterials, to return all the issues to the user with all the biomaterials belong to a submission. The user could correct all the issues in the submission and try archiving again. 
If we stop biomaterials processing after an error and return the result (error) to the user right away and more than one biomaterials would contain errors, then it would …

[dcp-745] Handle HTTPError from BioSamples service

---

hca/assay.py

Fixes issue
https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/770
Added
- check that an assay process should ONLY contain 1 sequencing and 1 library preparation protocol
- and derived files are all sequence files

dcp-770 updated assay check criteria

---

api/ingest.py
archiver/direct.py

dcp-771
Changes:
- Set submission status to Archived when metadata and data submission to archives was successful.

[dcp-771] Set submission status to Archived when success

---

README_for_direct_archiver.md

Changes:
- Added some missing steps and reformatted some paragraph in the archiver README.

Update direct archiving README with the new relevant steps

---

converter/biostudies.py
tests/unit/converter/test_biostudies_converter.py

dcp-819
Changes:
- Add default value for a specific project content

dcp-819 Fix project conversion for BioStudies
